language: python
python:
- 3.8
- 3.7
- 3.6 
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: grahamwetzler
  password:
    secure: LzxV0Lh/uKN2LIoLykX9xQFHuoVWjtvrpx9yuTHTsGmEln86Nu5MIjiU8HiRy5hPOhMAgw3zWcX3jqngCEbSH7JySFhG63Px7/kde9GKHdfGawptu7g2LyV7zc3d7dq1vYcLvIA+fY0Pg10p6aiq2P+tjHbRithXfgBfO8k/5lfW2UecmcBtu4ZrIQQNDUtXxq6Cg6Oe+fyrF8YWwBALKa0nOZSzXBedfnLgWJBhacSh+fPjRQoU9+AaRHOM4jzstFznMb4rGyBnfZvo6ofDOzi25jKljPcxJtsVkEOljJgnLePN4lKyF7PdBTCiYs4GgBjNiX68qKRD9dP9eNrI7WFDIaU9gXaxCISrNyfVFh997P6iuIdh84zOwj1TvxLEEPKIOMNkAfeAz1PrMHssZhcORA4xJzltHqBtkufPwH7OYswfqan+vGijy3ThPxchgg3s8jKDJ1moRnhcd8ro0uZtxFIYLRU68i7C0UerSg65qI5VnqueXGvbUM5ys77ojwUhxGDY+m4uljhgC/5RL09QY486bLHMo54xmQqUQf8u6l4VHffnMzYIhJTG++/shNpF6EGUkhUnNI9lkYw/QwSHfJg72+M5RRt/LYxmTBVwyO8dwxe29yXOWaSqLs9ycucp3zOb8sIfHcjjVs5jgdCGPYv3rlZ3O6WkAQ6o8UQ=
  on:
    tags: true
    repo: grahamwetzler/smart_meter_texas
    python: 3.8
